<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>

        <KSPBT_ModRoot>$(MSBuildThisFileDirectory)/GameData/KerbalismInterstellarCompat</KSPBT_ModRoot>
        <KSPBT_ModPluginFolder>plugins</KSPBT_ModPluginFolder>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="KSPBuildTools" Version="1.1.1" />
    </ItemGroup>
    
    <!-- Mod Dependencies -->
    <ItemGroup>
        <ModReference Include="Kerbalism">
            <DLLPath>GameData/Kerbalism/Kerbalism.dll</DLLPath>
            <CKANIdentifier>Kerbalism</CKANIdentifier>
        </ModReference>
    </ItemGroup>
    
</Project>
